### ISSUE TITLE
Support for cluster name

### ISSUE THREAD

**Issue by RomainSauvaire** [vinkla/pusher#11]
Hello there !

Pusher is setting up some clusters on different regions. Since I live in France I would like to use the `eu` but have no option to set it. Could you please tell me if it is planned or not (yet) ?

See the doc : https://pusher.com/docs/clusters

Thank you !

**Comment by vinkla** [comment]
Thanks for your suggestion! I'll take a look at it soon.

**Comment by vinkla** [comment]
You're of course welcome to submit a pull request for this.

**Comment by vinkla** [comment]
You can already do this? Add it to the options array.

```php
'options' => [
  'cluster' => 'APP_CLUSTER'
],
```

**Comment by RomainSauvaire** [comment]
Yeah I just noticed it, my bad.

I'll make a PR to update the documentation and state it clearly. 

Thank you and all my apologies

**Comment by vinkla** [comment]
No worries. I think the documentation is fine for now. Thanks anyway!

**Comment by realtebo** [comment]
@vinkla : please, update documentation ! I've the same problem and I don't know where must I add the 'options' array. Which is the config file to modify?

**Comment by vinkla** [comment]
@realtebo update the documentation yourself!
