### ISSUE TITLE
Unknown auth_key

### ISSUE THREAD

**Issue by duanp0128** [vinkla/pusher#13]
Why did I always get "Unknown auth_key" error? I can ensure that my app_key is right.

**Comment by vinkla** [comment]
This isn't an error thrown by this packages. 

@zimbatm what do you think about this?

**Comment by zimbatm** [comment]
@duanp0128 how did you setup your client ? This would happen if the credentials are missing.

**Comment by duanp0128** [comment]
@zimbatm Actually the credentials are missing in my server, but I set "encrypted" as false in "options" array. Is it responsible for the error?

**Comment by zimbatm** [comment]
If the credentials are missing then that's your issue. The "encrypted" option just tell the client whenever to use HTTPS or plain HTTP.

**Comment by duanp0128** [comment]
I see.  Thx.

**Comment by vinkla** [comment]
Okay, then I'll close this. Thanks for helping out @zimbatm!

**Comment by VerzatileTom** [comment]
@duanp0128 I had this problem too. While I'm following this workshop documentation https://pusher-community.github.io/real-time-laravel, the laravel log file shows this error. Well, I believe I have my keys written right on config/pusher.php.

**Comment by HamidVetr** [comment]
I have the same problem as @VerzatileTom

**Comment by bashirpour** [comment]
I had the same problem solved using the above method.
Thank you

**Comment by zutigrm** [comment]
Yup, Cluster solved that for me too.

Thanks =)

**Comment by kn100** [comment]
Awesome, glad to hear it!
