### ISSUE TITLE
Method 'trigger' not found in class \Vinkla\Pusher\PusherManager

### ISSUE THREAD

**Issue by Kryptonit3** [vinkla/pusher#5]
Well, I decided to give this package another go with Laravel 5.1. Not sure what the issue is. None of the Pusher SDK methods are available when I try your dependency injection method.

~~~
use Vinkla\Pusher\PusherManager;

class Foo
{
    protected $pusher;

    public function __construct(PusherManager $pusher)
    {
        $this->pusher = $pusher;
    }

    public function bar()
    {
        $this->pusher->trigger('my-channel', 'my-event', ['message' => $message]);
    }
}
~~~

Anyway to fix this so autocompletion will work?

**Comment by Kryptonit3** [comment]
also getting this when trying to use Facade
~~~
ErrorException in AbstractManager.php line 234: 

call_user_func_array() expects parameter 1 to be a valid callback, class 'Vinkla\Pusher\Facades\Pusher' does not have a method 'trigger'
~~~

**Comment by noprobz09** [comment]
Same here, I also encounter same issue, is there any other way to resolve the issue?

**Comment by Kryptonit3** [comment]
@noprobz09 just use this https://github.com/Kryptonit3/Pusher

**Comment by noprobz09** [comment]
Cool, Thanks, I will try this one.

**Comment by vinkla** [comment]
@Kryptonit3 please see #2 for facade usage. Could you provide your setup using the manager class?

**Comment by noprobz09** [comment]
I tried to install using the composer but the error says "could not find package krytonit3/pusher at any version for you minimum stability(stable). Check the package spelling or your minimum stabilty." Do you have any idea about this?

**Comment by noprobz09** [comment]
I tried this command "composer require kryptonit3/pusher"

**Comment by noprobz09** [comment]
By the way, I'm using Laravel 5.0

**Comment by Kryptonit3** [comment]
@noprobz09 try again. Forgot i had stability set to dev.

**Comment by noprobz09** [comment]
wow..... I really like your extension, I love this, I will recommend your extension. I really have trouble using some of the extension before, Its not really well documented, and it needs time to debug. Thank you for creating this very simple package but very really amazing extension ;) Keep it up :)

**Comment by vinkla** [comment]
Closing this. Please move the conversation to @Kryptonit3's Pusher package.

**Comment by shealan** [comment]
Can't get this to work in Laravel 5.2. Getting this "Method 'trigger' not found in class" error.
