### ISSUE TITLE
Config file

### ISSUE THREAD

**Issue by aris-b** [vinkla/pusher#8]
Hi,
I am having issues installing this package onto Lumen.

The config file located in config/pusher.php is completely ignored, instead the vendor/vinkla config file is used.

As far as i can see, the issue lies here:
https://github.com/vinkla/pusher/blob/master/src/PusherServiceProvider.php#L44:L46

**Comment by vinkla** [comment]
Did you [turn enable the configuration functionality](http://lumen.laravel.com/docs/installation#configuration-files)?

**Comment by vinkla** [comment]
Have you registered the service provider correctly?

**Comment by vinkla** [comment]
http://lumen.laravel.com/docs/installation#configuration-files

**Comment by aris-b** [comment]
I added this to app.php. 
```
$app->register('Vinkla\Pusher\PusherServiceProvider');
$app->configure('pusher');
```

Thanks @vinkla

**Comment by vinkla** [comment]
:+1:
