### ISSUE TITLE
vendor:publish -> Nothing to publish for tag[]

### ISSUE THREAD

**Issue by erikstainsby** [vinkla/pusher#9]
The vendor:publish command accompishes nothing. Have you gone away from using it? Do you need to update the installation docs?

**Comment by GrahamCampbell** [comment]
Looks like you forgot to register the service provider, or your services.json file needs deleting from the storage folder.

**Comment by vinkla** [comment]
@erikstainsby Did you register the service provider?

**Comment by erikstainsby** [comment]
That was my error. Thanks.
